### ISSUE TITLE
Broken link in "About"

### ISSUE THREAD

**Issue by Geet-George** [orcestra-campaign/livemap#1]
The [MQTT message specifications part](https://github.com/orcestra-campaign/livemap/blob/c8cdf30d70ab5c9170c88238b99374991a75d948/src/components/about.js#L16) in the About section has a URL that returns a 404 error. Currently, the URL is https://github.com/orcestra-campaign/mqtt_spec/blob/master/mqtt_spec.md

**Comment by d70-t** [comment]
There's now also an `mqtt_spec` for the orcestra campaign, thus the link now does lead to the right document.
Side-Note: The new orcestra spec now also includes platform types `uav` and `quadcopter`.
